[project]
name = "flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flow-matching>=1.0.10",
    "jupyterlab>=4.4.2",
    "matplotlib>=3.10.1",
    "notebook>=7.4.2",
    "scikit-learn>=1.6.1",
    "torch>=2.7.0",
    "torchaudio>=2.7.0",
    "torchvision>=0.22.0",
]
